config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :restaurants do
    resources :reviews , only: [:new, :create]
  end

  resources :reviews , only: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
    validates :name, presence: true
    validates :address, presence: true
    validates :phone_number, presence: true
    validates :category, presence: true, uniqueness: { case_sensitive: false }, acceptance: { accept: ["chinese", "italian", "japanese", "french", "belgian"] }
    has_many :reviews, dependent: :destroy
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant
  validates :content, presence: true, length: {minimum: 10}
  validates :rating, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
    before_action :find, only: [:show, :edit, :update, :destroy]
    def index
        @restaurant = Restaurant.all
    end

    def show;    end

    def new
        @restaurant = Restaurant.new
    end

    def create

        @restaurant = Restaurant.new(restaurant_params)
        if @restaurant.save
            redirect_to restaurants_path(@restaurant)
        else
            render :new
        end
    end

    def edit;    end

    def update
        @restaurant.update(restaurant_params)
        redirect_to restaurants_path(@restaurant)
    end

    def destroy
        @restaurant.destroy
        redirect_to restaurants_path
    end

    def restaurant_params
        params.require(:restaurant).permit(:name, :address, :phone_number, :category)
    end

    def find
        @restaurant = Restaurant.find(params[:id])
    end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
    before_action :find_restaurant, except: [:destroy]
    def new
        @review = Review.new
    end

    def show
    end

    def destroy
        @review = Review.find(params[:id])
        @review.destroy
        redirect_to restaurant_path(@review.restaurant)
    end

    def create
        @review = Review.new(review_params)
        @review.restaurant = @restaurant
        if @review.save
            redirect_to restaurant_path(@restaurant)
        else
            render :new
        end
    end

    private
    def find_restaurant
        @restaurant = Restaurant.find(params[:restaurant_id])
    end

    def review_params
        params.require(:review).permit(:content, :rating )
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurnts_helper.rb
module RestaurntsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelpMvp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/restaurants/_form.html.erb
<%=simple_form_for restaurant do |r| %>
    <%= r.input :name %>
    <%= r.input :address %>
    <%= r.input :phone_number %>
    <%= r.input :category %>
    <%= r.submit %>
<% end %>

app/views/restaurants/index.html.erb
<h1> My Restaurants <h1>
<%= link_to 'Create a new restaurant', new_restaurant_path %>
<% @restaurant.each do |r| %>
    <h4><%= link_to r.name, restaurant_path(r) %></h4>
    <% end %>

app/views/restaurants/new.html.erb
<%= render 'form', restaurant: @restaurant %>

app/views/restaurants/show.html.erb
<h1> <%= @restaurant.name %></h1>
<p> <%= @restaurant.address %></p>


<h1> <% @restaurant.reviews.each do |r| %></h1>
<p> <%= r.content %></p>
<%= link_to 'Delete Review', review_path(r), method: :delete %>
<% end %>

<%= link_to 'Back', restaurants_path %>
<%= link_to 'Edit Restaurant', edit_restaurant_path(@restaurant) %>
<%= link_to 'Destroy Restaurant', restaurants_path(@restaurant), method: :delete %>
<%= link_to 'Add Review', new_restaurant_review_path(@restaurant)%>

app/views/reviews/new.html.erb
<%= simple_form_for [ @restaurant, @review ] do |f| %>
    <%= f.input :content %>
    <%= f.input :rating %>
    <%= f.submit "Submit review", class: "btn btn-primary" %>
  <% end %>